# Generated by Django 3.1.7 on 2021-04-01 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('age', models.IntegerField()),
                ('img_Url', models.CharField(max_length=100)),
                ('bio', models.CharField(default=' ', max_length=50)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
