# Generated by Django 3.1.7 on 2021-04-21 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='bio',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='character',
            name='img_Url',
            field=models.CharField(max_length=400),
        ),
    ]
